/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.aircraftui;

import java.util.ArrayList;
import java.awt.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.FileWriter;

/**
 *
 * @author Usman Khan
 */
public class Cargo extends javax.swing.JFrame {
    
    public static Aircraft ac;
    public static DefaultTableModel dtm = new DefaultTableModel(0, 0);

    /**
     * Creates new form Cargo
     */
    public Cargo(Aircraft t) {
        initComponents();
        this.ac=t;
        ArrayList <Luggage> temp=ac.returnfun();
        head.setText("Welcome to "+t.airlineName+" Booking System");
        ownerName.setVisible(false);
        ownerNameField.setVisible(false);
        capacityLabel.setVisible(false);
        capacityField.setVisible(false);
        luggageIDLabel.setVisible(false);
        luggageIDField.setVisible(false);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addLuggageButton = new javax.swing.JToggleButton();
        removeLuggageButton = new javax.swing.JToggleButton();
        displayLuggageButton = new javax.swing.JToggleButton();
        ownerName = new javax.swing.JLabel();
        capacityLabel = new javax.swing.JLabel();
        ownerNameField = new javax.swing.JTextField();
        capacityField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        luggageIDLabel = new javax.swing.JLabel();
        luggageIDField = new javax.swing.JTextField();
        logoutButton = new javax.swing.JButton();
        submitButton = new javax.swing.JToggleButton();
        head = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        addLuggageButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addLuggageButton.setText("Add Luggage");
        addLuggageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLuggageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addLuggageButton);
        addLuggageButton.setBounds(245, 113, 143, 25);

        removeLuggageButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeLuggageButton.setText("Remove Luggage");
        removeLuggageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLuggageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(removeLuggageButton);
        removeLuggageButton.setBounds(245, 191, 143, 25);

        displayLuggageButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayLuggageButton.setText("Display Luggage");
        displayLuggageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayLuggageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(displayLuggageButton);
        displayLuggageButton.setBounds(245, 274, 143, 25);

        ownerName.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ownerName.setForeground(new java.awt.Color(255, 255, 255));
        ownerName.setText("Owner Name:");
        getContentPane().add(ownerName);
        ownerName.setBounds(245, 370, 110, 22);

        capacityLabel.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        capacityLabel.setForeground(new java.awt.Color(255, 255, 255));
        capacityLabel.setText("Capacity:");
        getContentPane().add(capacityLabel);
        capacityLabel.setBounds(245, 419, 90, 22);
        getContentPane().add(ownerNameField);
        ownerNameField.setBounds(365, 370, 140, 30);
        getContentPane().add(capacityField);
        capacityField.setBounds(365, 419, 140, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Luggage ID", "Owner Name", "Capacity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(968, 113, 452, 402);

        luggageIDLabel.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        luggageIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        luggageIDLabel.setText("Luggage ID:");
        getContentPane().add(luggageIDLabel);
        luggageIDLabel.setBounds(750, 370, 100, 22);
        getContentPane().add(luggageIDField);
        luggageIDField.setBounds(858, 370, 49, 30);

        logoutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logoutButton.setText("Home");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        getContentPane().add(logoutButton);
        logoutButton.setBounds(510, 520, 80, 25);

        submitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton);
        submitButton.setBounds(652, 518, 99, 25);

        head.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        getContentPane().add(head);
        head.setBounds(240, 30, 690, 50);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usman Khan\\Desktop\\Aircraft\\AircraftUI\\src\\main\\java\\com\\mycompany\\aircraftui\\aeroplane-wallpaper.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addLuggageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLuggageButtonActionPerformed
        // TODO add your handling code here:
        if(addLuggageButton.isSelected())
        {
            ownerName.setVisible(true);
            ownerNameField.setVisible(true);
            capacityLabel.setVisible(true);
            capacityField.setVisible(true);
            luggageIDLabel.setVisible(false);
            luggageIDField.setVisible(false);
        }
        else
        {
            ownerName.setVisible(false);
            ownerNameField.setVisible(false);
            capacityLabel.setVisible(false);
            capacityField.setVisible(false);
            luggageIDLabel.setVisible(false);
            luggageIDField.setVisible(false);
        }
    }//GEN-LAST:event_addLuggageButtonActionPerformed

    private void removeLuggageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLuggageButtonActionPerformed
        // TODO add your handling code here:
        if(removeLuggageButton.isSelected())
        {
            ownerName.setVisible(false);
            ownerNameField.setVisible(false);
            capacityLabel.setVisible(false);
            capacityField.setVisible(false);
            luggageIDLabel.setVisible(true);
            luggageIDField.setVisible(true);
        }
        else 
        {
            ownerName.setVisible(false);
            ownerNameField.setVisible(false);
            capacityLabel.setVisible(false);
            capacityField.setVisible(false);
            luggageIDLabel.setVisible(false);
            luggageIDField.setVisible(false);
            
        }
    }//GEN-LAST:event_removeLuggageButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        if(addLuggageButton.isSelected())
        {
            String oname = ownerNameField.getText();
            int cap = Integer.parseInt(capacityField.getText());
            int inp=JOptionPane.showConfirmDialog(this, "Do you want to proceed","Confirm",JOptionPane.YES_NO_OPTION);
            if(inp==0)
            {
                try{
                    ac.add(oname, cap);
                    JOptionPane.showMessageDialog(this,"Luggage Added","Success",JOptionPane.INFORMATION_MESSAGE);
                }catch(MyException e)
                {
                    JOptionPane.showMessageDialog(this,"Luggage Limit Exceeded","Fail",JOptionPane.ERROR_MESSAGE);
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Booking Aborted","Fail",JOptionPane.ERROR_MESSAGE);
            }
            
        }
        else if(removeLuggageButton.isSelected())
        {
            int id = Integer.parseInt(luggageIDField.getText());
            int inp=JOptionPane.showConfirmDialog(this, "Do you want to proceed","Confirm",JOptionPane.YES_NO_OPTION);
            if(inp==0)
            {
                try{
                    ac.delete(id);
                    System.out.println("Luggage Deleted");
                    JOptionPane.showMessageDialog(this,"Luggage Deleted","Success",JOptionPane.INFORMATION_MESSAGE);
                }catch(MyException e)
                {
                    JOptionPane.showMessageDialog(this,"No Luggage ID found","Fail",JOptionPane.ERROR_MESSAGE);
                }
                
            }else
            {
                JOptionPane.showMessageDialog(this,"Booking Aborted","Fail",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void displayLuggageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayLuggageButtonActionPerformed
        // TODO add your handling code here:
        ac.display();
        jTable1.removeAll();
        dtm.setRowCount(0);
        String header[] = new String[] {"Luggage ID","Owner Name","Capacity"};
        dtm.setColumnIdentifiers(header);
        jTable1.setModel(dtm);
        ArrayList <Luggage> temp=ac.returnfun();
        for(Luggage t: temp)
        {
            Vector<Object> data = new Vector<Object>();
            System.out.println(t.lid+"printing");
            data.add(t.lid);
            data.add(t.owner);
            data.add(t.kg);
            dtm.addRow(data);
        }
    }//GEN-LAST:event_displayLuggageButtonActionPerformed

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        new main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargo(ac).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addLuggageButton;
    private javax.swing.JTextField capacityField;
    private javax.swing.JLabel capacityLabel;
    private javax.swing.JToggleButton displayLuggageButton;
    private javax.swing.JLabel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField luggageIDField;
    private javax.swing.JLabel luggageIDLabel;
    private javax.swing.JLabel ownerName;
    private javax.swing.JTextField ownerNameField;
    private javax.swing.JToggleButton removeLuggageButton;
    private javax.swing.JToggleButton submitButton;
    // End of variables declaration//GEN-END:variables
}
