/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.aircraftui;

/**
 *
 * @author Prathamesh Kulkarni
 */
public class Login extends javax.swing.JFrame {
    
    String user;
    String pwd;
    /**
     * Creates new form Login
     */
    public Login() {
        this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        user = "Pentagon";
        pwd = "pentagon123";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        pwdField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        welcomeLabel.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("Welcome to Airline Reservation System");
        getContentPane().add(welcomeLabel);
        welcomeLabel.setBounds(470, 60, 608, 163);

        loginLabel.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setText("                                           Please enter login details");
        getContentPane().add(loginLabel);
        loginLabel.setBounds(400, 340, 645, 64);

        username.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username:");
        getContentPane().add(username);
        username.setBounds(640, 430, 120, 39);

        password.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password:");
        getContentPane().add(password);
        password.setBounds(640, 480, 100, 39);

        loginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFieldActionPerformed(evt);
            }
        });
        getContentPane().add(loginField);
        loginField.setBounds(760, 430, 150, 30);

        loginButton.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        loginButton.setText("Login");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(740, 600, 69, 27);
        getContentPane().add(pwdField);
        pwdField.setBounds(760, 480, 150, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(640, 550, 270, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usman Khan\\Desktop\\Aircraft\\AircraftUI\\src\\main\\java\\com\\mycompany\\aircraftui\\aeroplane-wallpaper.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -100, 2000, 1250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        
        String lgn = loginField.getText();
        char[] pd = pwdField.getPassword();
        
        String pwd1 = new String(pd);
        
        if(lgn.equals(user) && pwd1.equals(pwd)){
            new main().setVisible(true);
            this.dispose();
        }
        
        else if(lgn.isEmpty()){
            jLabel1.setText("Username missing!");
        }
        
        else if(pwd1.isEmpty()){
            jLabel1.setText("Password missing!");
        }
       
        else{
            jLabel1.setText("Wrong credentials. Please enter correct ones!");
            return;
        }
    }//GEN-LAST:event_loginButtonMouseClicked

    private void loginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField pwdField;
    private javax.swing.JLabel username;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
