/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.aircraftui;

import java.awt.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.FileWriter;

/**
 *
 * @author Usman Khan
 */
public class Passenger extends javax.swing.JFrame {

    /**
     * Creates new form Passenger
     */
    public  Aircraft ac;
    public static DefaultTableModel dtm = new DefaultTableModel(0, 0);
    
    public Passenger(Aircraft t) {
        
        initComponents();
        timer.setText("Welcome to "+t.airlineName+" Booking System");
        System.out.println("second frame");
        this.ac=t;
        System.out.println(ac.airlineName);
        passName.setVisible(false);
        points.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        tid.setVisible(false);
        jLabel3.setVisible(false);
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        RemovePassenger = new javax.swing.JToggleButton();
        AddPassenger = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        points = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passName = new javax.swing.JTextField();
        submit2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        displayPassenger = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        printTicket = new javax.swing.JToggleButton();
        timer = new javax.swing.JLabel();
        heading = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        RemovePassenger.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RemovePassenger.setText("Remove Passenger");
        RemovePassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovePassengerActionPerformed(evt);
            }
        });
        getContentPane().add(RemovePassenger);
        RemovePassenger.setBounds(43, 192, 150, 25);

        AddPassenger.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddPassenger.setText("Add Passenger");
        AddPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPassengerActionPerformed(evt);
            }
        });
        getContentPane().add(AddPassenger);
        AddPassenger.setBounds(43, 131, 141, 25);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Passenger Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 270, 140, 22);
        getContentPane().add(points);
        points.setBounds(150, 310, 153, 30);

        jLabel2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Flyer Points:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(43, 314, 110, 22);

        passName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passNameActionPerformed(evt);
            }
        });
        getContentPane().add(passName);
        passName.setBounds(190, 270, 153, 30);

        submit2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submit2.setText("Submit");
        submit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submit2MouseClicked(evt);
            }
        });
        getContentPane().add(submit2);
        submit2.setBounds(446, 412, 86, 25);

        jLabel3.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ticket Id:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(446, 270, 80, 22);
        getContentPane().add(tid);
        tid.setBounds(530, 270, 83, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket ID", "Seat No.", "Passenger Name", "Flight No.", "Fly Points"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(680, 130, 688, 402);

        displayPassenger.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayPassenger.setText("Display Passenger");
        displayPassenger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayPassengerMouseClicked(evt);
            }
        });
        getContentPane().add(displayPassenger);
        displayPassenger.setBounds(290, 192, 150, 25);

        logoutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logoutButton.setText("Home");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton);
        logoutButton.setBounds(320, 410, 80, 25);

        printTicket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printTicket.setText("Print Ticket");
        printTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printTicketActionPerformed(evt);
            }
        });
        getContentPane().add(printTicket);
        printTicket.setBounds(290, 131, 137, 25);

        timer.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        timer.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(timer);
        timer.setBounds(40, 30, 1050, 60);

        heading.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        heading.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usman Khan\\Desktop\\Aircraft\\AircraftUI\\src\\main\\java\\com\\mycompany\\aircraftui\\aeroplane-wallpaper.jpg")); // NOI18N
        getContentPane().add(heading);
        heading.setBounds(0, 0, 1980, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPassengerActionPerformed
        // TODO add your handling code here:
        if(AddPassenger.isSelected())
        {
            AddPassenger.setBackground(Color.LIGHT_GRAY);
            passName.setVisible(true);
            points.setVisible(true);
            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            tid.setVisible(false);
            jLabel3.setVisible(false);
            
        }
        else{
            AddPassenger.setBackground(null);
            passName.setVisible(false);
            points.setVisible(false);
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
            tid.setVisible(false);
            jLabel3.setVisible(false);
        }
    }//GEN-LAST:event_AddPassengerActionPerformed

    private void submit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit2MouseClicked
        // TODO add your handling code here:
        if(AddPassenger.isSelected())
        {
            String passname=passName.getText();
            int fp=Integer.parseInt(points.getText());
            int inp=JOptionPane.showConfirmDialog(this, "Do you want to proceed","Confirm",JOptionPane.YES_NO_OPTION);
            if(inp==0)
            {
                try{
                    ac.add(passname, fp);
                    System.out.println("Passenger Added");
                    JOptionPane.showMessageDialog(this,"Passenger Added","Success",JOptionPane.INFORMATION_MESSAGE);
                }
                catch(MyException e)
                {
                    e.print();
                    JOptionPane.showMessageDialog(this,"Sorry Seats Full","Fail",JOptionPane.ERROR_MESSAGE);
                }
                
                
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Booking Aborted","Fail",JOptionPane.ERROR_MESSAGE);
            }
                
            
        }
        else if(RemovePassenger.isSelected())
        {
            int ticId=Integer.parseInt(tid.getText());
            int inp=JOptionPane.showConfirmDialog(this, "Do you want to proceed","Confirm",JOptionPane.YES_NO_OPTION);
            if(inp==0)
            {
                try{
                    ac.delete(ticId);
                    System.out.println("Passenger Deleted");
                    JOptionPane.showMessageDialog(this,"Passenger Deleted","Success",JOptionPane.INFORMATION_MESSAGE);
                }
                catch(MyException e)
                {
                    e.print();
                    JOptionPane.showMessageDialog(this,"Ticket ID not found","Fail",JOptionPane.ERROR_MESSAGE);
                }
                
                
            }else
            {
                JOptionPane.showMessageDialog(this,"Deletion Failed","Fail",JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
        else if(printTicket.isSelected())
        {
            int ticId=Integer.parseInt(tid.getText());
            ArrayList <Ticket> temp=ac.returnfun();
            int flag=0;
            for(Ticket t:temp)
            {
                if(t.tid==ticId)
                {
                    System.out.println("TIcket found");
                    flag=1;
                    String fname=ticId+".txt";
                    try
                    {
                       FileWriter fw=new FileWriter(fname);
                       fw.write("Welcome Onboard, Happy to Serve you\n");
                       fw.write("=============================\n");
                       fw.write("Name : "+t.p.passName+"\t"+"Flight No: "+ac.flightnum+"\n");
                       fw.write("FROM : "+ac.departure+"~-~-~-~-~-~-~-~-~"+"TO : "+ac.arrival+"\n");
                       fw.write("Seat No: "+t.seatNum+"\n");
                       fw.write("Please make sure you start boarding 45 minutes prior to the departure time!");
                       fw.close();
                    }catch(Exception e){System.out.println(e);}  
                    System.out.println("Write successful");
                    JOptionPane.showMessageDialog(this,"Ticket Generated","Success",JOptionPane.INFORMATION_MESSAGE);
                       
                }
            }
            if(flag==0)
                JOptionPane.showMessageDialog(this,"Ticket not Found","Fail",JOptionPane.ERROR_MESSAGE);
        
        }
        
        
    }//GEN-LAST:event_submit2MouseClicked

    private void RemovePassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovePassengerActionPerformed
        // TODO add your handling code here:
        if(RemovePassenger.isSelected())
        {
            RemovePassenger.setBackground(Color.LIGHT_GRAY);
            tid.setVisible(true);
            jLabel3.setVisible(true);
            passName.setVisible(false);
            points.setVisible(false);
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
            
        }
        else{
            RemovePassenger.setBackground(null);
            tid.setVisible(false);
            jLabel3.setVisible(false);
            passName.setVisible(false);
            points.setVisible(false);
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
        }
    }//GEN-LAST:event_RemovePassengerActionPerformed

    private void displayPassengerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayPassengerMouseClicked
        // TODO add your handling code here:
        ac.display();
        jTable1.removeAll();
        dtm.setRowCount(0);
        String header[] = new String[] { "Ticket Id", "Seat No", "Passenger Name",
        "Flight No", "Fly Points"};
        dtm.setColumnIdentifiers(header);
        jTable1.setModel(dtm);
        ArrayList <Ticket> temp=ac.returnfun();
        for(Ticket t: temp)
        {
            Vector<Object> data = new Vector<Object>();
            System.out.println(t.tid+"printing");
            data.add(t.tid);
            data.add(t.seatNum);
            data.add(t.p.passName);
            data.add(t.p.flightnum);
            data.add(t.p.flyPoints);
            dtm.addRow(data);
        }
    }//GEN-LAST:event_displayPassengerMouseClicked

    private void printTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printTicketActionPerformed
        // TODO add your handling code here:
        if(printTicket.isSelected())
        {
            printTicket.setBackground(Color.LIGHT_GRAY);
            tid.setVisible(true);
            jLabel3.setVisible(true);
            passName.setVisible(false);
            points.setVisible(false);
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
            
        }
        else{
            printTicket.setBackground(null);
            tid.setVisible(false);
            jLabel3.setVisible(false);
            passName.setVisible(false);
            points.setVisible(false);
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
        }
    }//GEN-LAST:event_printTicketActionPerformed

    private void passNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passNameActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        
        ArrayList <Ticket> temp=ac.returnfun();
        
        
        
                    try
                    {
                       FileWriter fw=new FileWriter("log.txt");
                       fw.write("Name\tFlight No\tDeparture City\tArrival City\tSeat num\n");
                       for(Ticket t:temp)
                       {           
                            fw.write(t.p.passName+"\t"+ac.flightnum+"\t");
                            fw.write(ac.departure+"\t"+ac.arrival+"\t");
                            fw.write(t.seatNum+"\n");
                            
                       }
                       fw.close();
                    }catch(Exception e){System.out.println(e);}  
                    System.out.println("Write successful");
                    
                    
                       
                
            
        JOptionPane.showMessageDialog(this,"Log Generated","Success",JOptionPane.INFORMATION_MESSAGE);
        new main().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Passenger(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JToggleButton AddPassenger;
    public static javax.swing.JToggleButton RemovePassenger;
    public static javax.swing.JButton displayPassenger;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutButton;
    public static javax.swing.JTextField passName;
    public static javax.swing.JTextField points;
    public static javax.swing.JToggleButton printTicket;
    public static javax.swing.JButton submit2;
    public static javax.swing.JTextField tid;
    private javax.swing.JLabel timer;
    // End of variables declaration//GEN-END:variables
}
